# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Cyberspace Web Docs
site_url: https://aohk22.github.com/cyberspace-academy
repo_url: https://github.com/aohk22/cyberspace-academy
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Explaination: explanation.md
  - Reference:
      - Database Schematic: reference/database-schematic.md
      - Sitemap: reference/sitemap.md
  - Feature Tracking:
      - Challenges: feature-tracking/challenges.md
      - Admin Dashboard: feature-tracking/admin-dashboard.md
      - Learning Paths: feature-tracking/admin-dashboard.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

plugins:
  - search
  - panzoom:
      always_show_hint: true
      hint_location: "top"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
